sudo: required

services:
  - docker

before_install:
  - docker build -t claralie/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true claralie/docker-react npm run test -- --coverage

language: generic