sudo: required

services:
  - docker

before_install:
  - docker build -t claralie/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true claralie/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-929477561799"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY